---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Python Lint

on:
  - pull_request

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@eb1897b8dc4b5d5bfe39a428a8f2304605e0983c # v7.0.0

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras

      - name: Run ruff format
        run: uv run ruff format --check .

      - name: Run ruff check
        run: uv run ruff check .

      - name: Run ruff uv lock check
        run: uv lock --check
