# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Check uv.lock Freshness

on:
  pull_request:
    paths:
      - "pyproject.toml"
      - "uv.lock"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-uv-lock:
    if: github.actor == 'renovate[bot]' || startsWith(github.head_ref, 'renovate/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.head_ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2

      - name: Ensure lock is up to date
        run: uv lock --check
